---
- name: Basic Software
  ansible.builtin.apt:
    name:
      - git
      - screen
      - zip
      - unzip
      - wget
      - curl
      - jq

- name: Copy installer.sh
  ansible.builtin.copy:
    src: installer
    dest: /root/
    mode: '0755'

- name: start installer aus
  ansible.builtin.command:
    cmd: bash /root/installer
