#!/bin/bash


yamlFiles=(
    "media.yml"
    "ssh.yml"
    "run.yml"
)

read -p "Enter the IP address of the server: " server_ip
read -p "Enter the config to use (media.yml/run.yml/ssh.yml): " yaml_file
read -p "enter the path of your Private Key: " private_key_path

if [[ ! " ${yamlFiles[@]} " =~ " ${yaml_file} " ]]; then
    echo "Invalid yaml file. Please choose from: ${yamlFiles[*]}"
    exit 1
fi
if [[ -z "$server_ip" ]]; then
    echo "Server IP cannot be empty."
    exit 1
fi
if [[ ! -f "$private_key_path" ]]; then
    echo "Private key file does not exist."
    exit 1
fi

cp -a $private_key_path $(PWD)/Conf/roles/ssh/files
chmod 600 $(PWD)/Conf/roles/ssh/files

echo "[myhosts] $(server_ip) " > hosts.ini

ansible-playbook -i hosts.ini "$yaml_file"