---
- name: Start Home Server Automation
  ansible.builtin.debug:
    msg: "Starting Home Server Automation"

- name: copy docker-compose.yaml file
  ansible.builtin.copy:
    src: docker-compose.yaml
    dest: /root/docker-compose.yaml
    mode: '0755'

- name: create directorys, if not exits and move config files
  ansible.builtin.copy:
    src: config
    dest: /root/
    mode: '0755'

- name: start create file
  ansible.builtin.command:
    cmd: bash /root/config/create

- name: start docker compose with config
  ansible.builtin.command:
    cmd: docker compose -f /root/docker-compose.yaml up -d
