---

- name: copy ssh configuration
  ansible.builtin.copy:
    src: sshd_config
    dest: /etc/ssh/
    owner: root
    mode: '0644'

#- name: Restart service ssh
#   ansible.builtin.service:
#    name: sshd
#    state: restarted

- name: Copy private key
  ansible.builtin.copy:
    src: id_rsa
    dest: /root/.ssh/id_rsa
    owner: root
    mode: '0600'

#- name: Set authorized key taken from file
#  ansible.posix.authorized_key:
#    user: root
#    state: present
#    key: "Schniedel Key"

- name: ufw allow ssh
  community.general.ufw:
    rule: allow
    name: OpenSSH