#!/bin/bash

if command -v docker &> /dev/null; then
    echo "✅ Docker is installed."
    docker --version
else
    # Add Docker's official GPG key:
    sudo apt-get update
    sudo apt-get install ca-certificates curl
    sudo install -m 0755 -d /etc/apt/keyrings
    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc

    # Add the repository to Apt sources:
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update

    sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
fi

asset_name="rathole-x86_64-unknown-linux-gnu.zip"

test=$(wget https://github.com/rapiz1/rathole/releases/latest/download/$asset_name)

echo "Downloaded $test"

# Unpack the downloaded archive
uzip $asset_name


# Move the binary to a directory in your system's PATH
sudo mv rathole /usr/local/bin/

# Verify installation
rathole -V