version: "3.9"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    volumes:
      - ./config/sonarr:/config
      - ${TVSHOWS}:/tv 
      - ${DOWNLOADS}:/downloads 
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    ports:
      - 7878:7878
    volumes:
      - ./config/radarr:/config
      - ${MOVIES}:/movies
      - ${DOWNLOADS}:/downloads
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    volumes:
      - ./config/jellyfin:/config
      - ${TVSHOWS}:/data/tvshows
      - ${MOVIES}:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    volumes:
      - ./config/sabnzbd:/config
      - ${DOWNLOADS}:/downloads
      - ${INCOMPLETE_DOWNLOADS}:/incomplete-downloads
    ports:
      - 8080:8080
    restart: unless-stopped
