- name: Server Infrastructure Setup
  ansible.builtin.debug:
    msg: "Setting up server infrastructure with Ansible"


- name: start ufw
  community.general.ufw:
    state: enabled
    policy: deny


- name: Add samba share configuration to smb.conf
  blockinfile:
    path: "/etc/samba/smb.conf"
    block: |
      [Storage]
      path = /mnt/storage
      public = yes
      writeable = yes

- name: Restart Samba service
  service:
    name: smbd
    state: restarted
