---

- name: Copy installer.sh
  ansible.builtin.copy:
    src: installer.sh
    dest: /root/
    mode: '0755'

- name: führe installer.sh aus
  ansible.builtin.command:
    cmd: bash /root/installer.sh


